version: '3.8'
name: ms-services
services:
  redis:
    image: redis:6.2.5
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - ms-service
  redislnsight:
    image: redis/redisinsight:latest
    hostname: redislnsight
    container_name: redislnsight
    restart: always
    volumes:
      - ./dist/redisinsight:/data
    ports:
      - '8001:5540'
    environment:
      REDISINSIGHT_REDIS_URI: 'redis://redis:6379'
    networks:
      - ms-service
networks:
  ms-service:
    name: ms-service